### PR TITLE
Functioning character, ability and level select widgets

### PR DESCRIPTION
**Pull request by Nanitus**

### CODE REVIEW

**Comment by Cjor100** [comment]
Delete Fallen_World/Saved/Config/Windows/EditorPerProjectUserSettings.ini to remove the merge conflict

**Comment by Cjor100** [comment]
you have a whole lot more issues now that you pulled from master

**Comment by Nanitus** [comment]
It only said there was one conflict when I pushed, what other errors are
there?

**Comment by Cjor100** [comment]
Conflicting files
Fallen_World/Content/Abilities/AbilitiesTestLevelDustin.umap
Fallen_World/Content/Abilities/Blueprints/BP_DefensiveAbility.uasset
Fallen_World/Content/Abilities/Blueprints/BP_DropOilSlick.uasset
Fallen_World/Content/Abilities/Blueprints/BP_OffsensiveAbility.uasset
Fallen_World/Content/Abilities/Blueprints/BP_PassiveAbility.uasset
Fallen_World/Content/Abilities/Blueprints/BP_ShockWave.uasset
Fallen_World/Content/Level_Design/Maps_assets/Maps/LevelDesign_Default1.umap
Fallen_World/Content/Physics_And_Ai/Physics/Temp_Test_Car/BP_TestCarH.uasset
Fallen_World/Content/Physics_And_Ai/Physics/Temp_Test_Car/UI_TestFeulHud.uasset
Fallen_World/Saved/Config/Windows/EditorPerProjectUserSettings.ini

**Pull request closed without merging**
